# ------------------------------------------------------#
# Deus config file                                      #
# https://github.com/CrudelisDeus/hyprland-dotfiles.git #
# ------------------------------------------------------#

[font]
size = 10

builtin_box_drawing = true

[font.normal]
family = "JetBrainsMono Nerd Font"